### ISSUE TITLE
Seriously It's Support Pouchdb ?

### ISSUE THREAD

**Issue by Nebula-Spark** [lohanidamodar/angular2-electron-quickstart#1]
Hi , 
pouchdb-node  not working , getting a following error !
![leveldb adapter not working](https://cloud.githubusercontent.com/assets/2277794/18554167/efb857da-7b80-11e6-89b7-4fc09ee6a5ba.jpg)

**Comment by lohanidamodar** [comment]
I am using browserify to support pouchdb
`npm install pouchdb` 
not node-pouchdb
