### ISSUE TITLE
Npm Run Electron  --  ERROR !

### ISSUE THREAD

**Issue by Nebula-Spark** [lohanidamodar/angular2-electron-quickstart#2]
Hi ,

npm run electron     ==  Gives the following Error....

 Failed to load resource: net::ERR_FILE_NOT_FOUND  file:///C:/Portal/dist/electron-package/js/bundle.js 

There is No bundle.js file inside  electron-package/js
![bundle error](https://cloud.githubusercontent.com/assets/2277794/18553403/ec7583d4-7b7d-11e6-9c30-789cf16c91ec.jpg)

When i Manually copy the bundel.js from fronted to electron package/js

IT WORKS !
![budleworks](https://cloud.githubusercontent.com/assets/2277794/18553473/2bfc9c90-7b7e-11e6-9e1d-a20bfd1c2618.jpg)

**Comment by lohanidamodar** [comment]
please pull the recent version, it is fixed
